Repository traveli-dev/traveli-web, pull requests merged in 2022-07, with the labels that each got.

#45 🦩Iconにchakra-uiのスタイルが当たるように修正
  README.md
  front/src/components/Icons/IconCamera.tsx
  front/src/components/Icons/IconEdit.tsx
  front/src/components/Icons/IconHelp.tsx
  front/src/components/Icons/IconLink.tsx
  front/src/components/Icons/IconMenu.tsx
  front/src/components/Icons/IconPlus.tsx
  front/src/components/Icons/IconQr.tsx
  front/src/components/Icons/IconReturn.tsx
  front/src/components/Icons/IconSave.tsx
  front/src/components/Icons/IconShare.tsx
  front/src/components/Icons/IconSignOut.tsx
  front/src/components/Icons/IconUser.tsx
  front/src/components/Icons/IconViewGrid.tsx
  front/src/components/Icons/IconViewList.tsx
  front/src/pages/home.tsx
Labels: Review Required, issue

#48 :pig: 画像アップロード（ユーザページ）実装
  front/.eslintrc.js
  front/src/hooks/auth/useSignInAnonymously.ts
  front/src/pages/user.tsx
  front/src/types/db/index.ts
  front/src/types/db/user/user.ts
Labels: Review Required

#46 📚 storybook導入と使い回すコンポーネントを作る
  .github/workflows/gh-pages.yml
  .github/workflows/push.yml
  README.md
  docker-compose.yml
  front/.eslintrc.js
  front/.prettierrc.js
  front/.storybook/main.js
  front/.storybook/preview.tsx
  front/package.json
  front/src/components/Buttons/Button.tsx
  front/src/components/Buttons/ButtonIconRound.tsx
  front/src/components/Buttons/index.ts
  front/src/components/Icons/IconEdit.tsx
  front/src/components/Icons/IconPlus.tsx
  front/src/stories/components/Buttons/Button.stories.tsx
  front/src/stories/components/Buttons/ButtonIconRound.stories.tsx
  front/src/stories/components/Colors/Colors.stories.tsx
  front/src/stories/components/Icons/Icons.stories.tsx
  front/src/theme/button.ts
  front/src/theme/index.ts
  front/yarn.lock
Labels: Review Required, Markup

#51 👍 inputコンポーネント作成
  front/src/components/Inputs/Input.tsx
  front/src/components/Inputs/index.ts
  front/src/stories/components/Buttons/Button.stories.tsx
  front/src/stories/components/Buttons/ButtonIconRound.stories.tsx
  front/src/stories/components/Inputs/Input.stories.tsx
Labels: Markup, 🥳LGTM

#62 🙄/homeページのマークアップ
  front/public/images/dummy.png
  front/public/images/traveli.svg
  front/src/components/Layout/Layout.tsx
  front/src/pages/home.tsx
  front/src/public/images/dummy.png
  front/src/public/images/traveli.svg
Labels: Review Required, Markup

#64 🚲文字のジャギりを修正
  front/src/theme/index.ts
Labels: 🥳LGTM, bug, issue

#52 :snake: userページのリファクタリング
  front/src/components/Forms/FormUserProfile.tsx
  front/src/components/Forms/index.ts
  front/src/hooks/form/index.ts
  front/src/hooks/form/useCreateUpdateUserProfile.ts
  front/src/pages/user.tsx
Labels: Logic, 🥳LGTM

#65 🥇 Createページのロジック作成
  front/src/components/Forms/FormCreateLinks.tsx
  front/src/components/Forms/index.ts
  front/src/hooks/firestore/index.ts
  front/src/hooks/firestore/travelink/useCreateTravelink.ts
  front/src/hooks/firestore/travelink/useGetTravelink.ts
  front/src/hooks/form/index.ts
  front/src/hooks/form/useFormCreateLinks.ts
  front/src/hooks/upload/index.ts
  front/src/hooks/upload/useUploadImage.ts
  front/src/pages/[traveliId]/edit.tsx
  front/src/pages/[traveliId]/index.tsx
  front/src/pages/create.tsx
  front/src/pages/edit.tsx
  front/src/public/images/dummy.png
  front/src/public/images/traveli.svg
  front/src/types/db/index.ts
  front/src/types/db/travelink.ts
  front/src/types/db/user.ts
Labels: Logic, 🥳LGTM

#76 🥞/userページの作成
  front/src/components/Forms/FormUserProfile.tsx
  front/src/hooks/form/useCreateUpdateUserProfile.ts
  front/src/theme/index.ts
Labels: Markup

#83 :earth_americas: ページ遷移を一部つけた
  front/next.config.js
  front/src/components/Forms/FormUserProfile.tsx
  front/src/pages/home.tsx
Labels: Review Required, Logic

#91 :cow: /userの不具合を治す
  front/src/components/Forms/FormUserProfile.tsx
  front/src/hooks/form/useCreateUpdateUserProfile.ts
  front/src/theme/index.ts
Labels: 🥳LGTM, bug

#87 🥐CardLinkコンポーネントを作成
  front/src/components/Cards/CardLink.tsx
  front/src/pages/home.tsx
Labels: Markup, 🥳LGTM

#92 🍞 Editページロジック作成
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/components/Forms/index.ts
  front/src/hooks/firestore/index.ts
  front/src/hooks/firestore/profile/useGetOwnerProfile.ts
  front/src/hooks/firestore/travelink/useUpdateTravelink.ts
  front/src/hooks/form/index.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/hooks/role/index.ts
  front/src/hooks/role/useRoleEdit.ts
  front/src/hooks/upload/useUploadImage.ts
  front/src/pages/[traveliId]/edit.tsx
  front/src/pages/create.tsx
  front/src/pages/home.tsx
Labels: Logic, 🥳LGTM

#98 :bomb: /idページのマークアップと少しのロジック実装
  front/src/components/Buttons/ButtonViewChange.tsx
  front/src/components/Buttons/index.ts
  front/src/components/Cards/CardLink.tsx
  front/src/components/Cards/index.ts
  front/src/pages/[traveliId]/index.tsx
  front/src/pages/home.tsx
  front/src/theme/colors.ts
  front/src/theme/index.ts
Labels: Review Required, Logic, Markup

#100 🥨 datepicker導入する
  front/package.json
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/components/Inputs/InputDate.tsx
  front/src/components/Inputs/index.ts
  front/src/hooks/firestore/travelink/useCreateTravelink.ts
  front/src/hooks/firestore/travelink/useUpdateTravelink.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/pages/[traveliId]/index.tsx
  front/src/pages/home.tsx
  front/src/theme/index.ts
  front/src/types/db/travelink.ts
  front/yarn.lock
Labels: Review Required, Logic

#102 firebaseでデプロイする
  .github/workflows/firebase-hosting-merge.yml
  front/.firebaserc
  front/.gitignore
  front/firebase.json
  front/package.json
  front/yarn.lock
Labels: Review Required

#96 🥗/homeにcreateボタンを追加する
  front/src/pages/home.tsx
Labels: Review Required, Markup

#104 🥦 React18のエラーえぐくて草
  front/package.json
  front/src/components/Inputs/InputDate.tsx
  front/src/theme/index.ts
  front/yarn.lock
Labels: 🥳LGTM

#116 🥙DatePickerの見た目をどうにかしてみる
  front/package.json
  front/src/components/Inputs/InputDate.tsx
  front/src/components/Inputs/date-picker.css
  front/src/pages/_app.tsx
  front/yarn.lock
Labels: Markup, 🥳LGTM

#112 :snowboarder: サイドメニューの作成
  front/src/components/Sidebars/Sidebar.tsx
  front/src/components/Sidebars/index.ts
  front/src/pages/home.tsx
Labels: Markup, 🥳LGTM

#110 :blossom: QRコードモーダルの作成
  front/public/images/traveli-logo.svg
  front/src/components/Modals/ModalQrCode.tsx
  front/src/components/Modals/index.ts
  front/src/pages/[traveliId]/index.tsx
Labels: Logic, Markup, 🥳LGTM

#113 :bow: 404ページの作成
  front/public/images/person_bowing.svg
  front/src/hooks/auth/useCheckAuth.tsx
  front/src/hooks/firestore/travelink/useGetTravelink.ts
  front/src/pages/404.tsx
Labels: Logic, Markup, 🥳LGTM

#119 📘 保存機能を作る
  front/public/images/icons/bookmark-outline.svg
  front/public/images/icons/bookmark-solid.svg
  front/src/components/Cards/CardHome.tsx
  front/src/components/Cards/index.ts
  front/src/components/Tabs/TabHome.tsx
  front/src/components/Tabs/index.ts
  front/src/hooks/button/index.ts
  front/src/hooks/button/useButtonBookmark.ts
  front/src/hooks/firestore/bookmark/useCheckBookmarked.ts
  front/src/hooks/firestore/bookmark/useCreateBookmark.ts
  front/src/hooks/firestore/bookmark/useDeleteBookmark.ts
  front/src/hooks/firestore/bookmark/useGetBookmarkList.ts
  front/src/hooks/firestore/index.ts
  front/src/pages/[traveliId]/index.tsx
  front/src/pages/home.tsx
  front/src/theme/colors.ts
  front/src/types/db/bookmark.ts
  front/src/types/db/index.ts
Labels: Logic, 🥳LGTM

#134 🥫 カテゴリー機能の実装
  front/src/components/Cards/CardEdit.tsx
  front/src/components/Cards/CardEditWrapper.tsx
  front/src/components/Cards/CardLink.tsx
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/components/Radios/RadioCategoryItem.tsx
  front/src/components/Radios/RadioCategoryList.tsx
  front/src/components/Radios/index.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/hooks/radio/index.ts
  front/src/hooks/radio/useRadioCategory.ts
  front/src/pages/[traveliId]/index.tsx
  front/src/types/db/index.ts
  front/src/types/db/travelink.ts
Labels: Logic, 🥳LGTM

#130 📅日時の文字色修正
  front/src/components/Inputs/date-picker.css
Labels: Markup, 🥳LGTM

#135 📆 dateをからでも登録できるようにする
  front/src/hooks/form/useFormCreateUpdateLinks.ts
Labels: Review Required, Logic, bug

#143 🏃 初回登録時の遷移先の修正
  front/src/hooks/auth/useCheckAuth.tsx
  front/src/hooks/auth/useSignInAnonymously.ts
  front/src/hooks/firestore/index.ts
  front/src/hooks/firestore/user/useCreateUser.ts
  front/src/hooks/form/useCreateUpdateUserProfile.ts
  front/src/recoil/atoms/history.ts
  front/src/recoil/atoms/index.ts
  front/src/recoil/keys.ts
Labels: Logic, bug

#149 🇪🇷 コンソールエラーの修正
  front/src/components/Cards/CardHome.tsx
  front/src/components/Forms/FormUserProfile.tsx
  front/src/hooks/filter/index.ts
  front/src/hooks/filter/useFilterTravelink.ts
  front/src/pages/[traveliId]/index.tsx
Labels: 🥳LGTM, bug

#144 ⚫ ローディング中にSpinnerを表示する
  front/src/components/Cards/CardHome.tsx
  front/src/components/Forms/FormUserProfile.tsx
  front/src/components/Loadings/Loading.tsx
  front/src/components/Loadings/index.ts
  front/src/hooks/auth/useCheckAuth.tsx
  front/src/hooks/filter/index.ts
  front/src/hooks/filter/useFilterTravelink.ts
  front/src/pages/[traveliId]/edit.tsx
  front/src/pages/[traveliId]/index.tsx
  front/src/pages/create.tsx
  front/src/pages/home.tsx
Labels: Markup, 🥳LGTM

#156 🩹 色々修正
  front/src/components/Cards/CardEditWrapper.tsx
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/components/Forms/FormUserProfile.tsx
  front/src/components/Sidebars/Sidebar.tsx
  front/src/hooks/button/useButtonBookmark.ts
  front/src/hooks/firestore/bookmark/useCheckBookmarked.ts
  front/src/hooks/firestore/bookmark/useCreateBookmark.ts
  front/src/hooks/firestore/bookmark/useDeleteBookmark.ts
  front/src/hooks/firestore/bookmark/useGetBookmarkList.ts
  front/src/hooks/firestore/index.ts
  front/src/hooks/firestore/profile/useGetOwnerProfile.ts
  front/src/hooks/firestore/user/useCreateUser.ts
  front/src/hooks/firestore/user/useGetUser.ts
  front/src/hooks/firestore/user/useUpdateUser.ts
  front/src/hooks/form/index.ts
  front/src/hooks/form/useCreateUpdateUserProfile.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/hooks/form/useFormCreateUpdateUser.ts
  front/src/hooks/input/index.ts
  front/src/hooks/input/useInputImage.ts
  front/src/pages/create.tsx
  front/src/pages/home.tsx
  front/src/pages/user.tsx
  front/src/recoil/atoms/user.ts
  front/src/types/db/index.ts
  front/src/types/db/user.ts
Labels: 🥳LGTM, bug

#159 色々修正part2
  front/src/components/Cards/CardEdit.tsx
  front/src/components/Cards/CardEditWrapper.tsx
  front/src/components/Cards/CardLink.tsx
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/hooks/api/index.ts
  front/src/hooks/api/useFetchOgp.ts
  front/src/pages/api/ogp.ts
Labels: Logic, 🥳LGTM, refactor

#164 色々修正part3
  front/public/images/icons/food.svg
  front/public/images/icons/other.svg
  front/public/images/icons/place.svg
  front/src/components/Buttons/Button.tsx
  front/src/components/Buttons/ButtonIconRound.tsx
  front/src/components/Buttons/ButtonViewChange.tsx
  front/src/components/Buttons/index.ts
  front/src/components/Cards/CardEdit.tsx
  front/src/components/Cards/CardEditWrapper.tsx
  front/src/components/Cards/CardHome.tsx
  front/src/components/Cards/CardLink.tsx
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/components/Menus/MenuLinkCardEdit.tsx
  front/src/components/Menus/index.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/pages/[traveliId]/index.tsx
  front/src/pages/home.tsx
Labels: 🥳LGTM, refactor
