Repository traveli-dev/traveli-web, pull requests merged in 2022-09, with the labels that each got.

#184 💯 カテゴリーもRHFで管理する など
  front/src/components/Auth/CheckAuth.tsx
  front/src/components/Auth/index.ts
  front/src/components/Cards/CardEdit.tsx
  front/src/components/Cards/CardEditWrapper.tsx
  front/src/components/Cards/CardLink.tsx
  front/src/components/Cards/CardLinkEdit.tsx
  front/src/components/Cards/CardLinkEditList.tsx
  front/src/components/Cards/index.ts
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/components/Inputs/InputDate.tsx
  front/src/components/Menus/MenuCardLinkEdit.tsx
  front/src/components/Menus/index.ts
  front/src/components/Radios/RadioCategory.tsx
  front/src/components/Radios/RadioCategoryItem.tsx
  front/src/components/Radios/RadioCategoryList.tsx
  front/src/components/Radios/index.ts
  front/src/hooks/api/useFetchOgp.ts
  front/src/hooks/auth/index.ts
  front/src/hooks/auth/useCheckAuth.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/hooks/radio/index.ts
  front/src/hooks/radio/useRadioCategory.ts
  front/src/pages/[traveliId]/index.tsx
  front/src/pages/_app.tsx
  front/src/pages/api/ogp.ts
  front/src/types/db/index.ts
  front/src/types/db/travelink.ts
Labels: Review Required, refactor

#190 IDページの認証を外すなど
  front/public/images/smartphone-mini.png
  front/src/components/Buttons/ButtonSignIn.tsx
  front/src/components/Modals/ModalSignIn.tsx
  front/src/components/Modals/index.ts
  front/src/hooks/auth/useCheckAuth.ts
  front/src/hooks/button/useButtonBookmark.ts
  front/src/hooks/firestore/travelink/useGetTravelink.ts
  front/src/pages/[traveliId]/index.tsx
  front/src/stories/__snapshots__/Storyshots.test.ts.snap
  front/src/stories/components/Cards/CardHome.stories.tsx
  front/src/stories/components/Cards/CardLink.stories.tsx
  front/src/stories/components/Cards/CardLinkEdit.stories.tsx
  front/src/stories/components/Loadings/Loading.stories.tsx
  front/src/stories/components/Menus/MenuCardLinkEdit.stories.tsx
  front/src/stories/components/Modals/ModalQrCode.stories.tsx
  front/src/stories/components/Radios/RadioCategory.stories.tsx
  front/src/stories/components/Tabs/TabHome.stories.tsx
Labels: Review Required, Logic

#199 🖼サムネイル未設定時に表示するデフォルト画像を設定
  front/public/images/noImage.png
  front/public/images/noImage_icon.png
  front/public/images/noImage_icon_lg.png
  front/src/components/Cards/CardHome.tsx
  front/src/pages/[traveliId]/index.tsx
Labels: Markup, 🥳LGTM

#180 🍞エラー時に表示するトーストの作成
  front/package.json
  front/public/images/error.svg
  front/public/images/success.svg
  front/src/components/Toasts/BaseToastContainer.tsx
  front/src/components/Toasts/baseToastContainer.css
  front/src/components/Toasts/index.tsx
  front/src/hooks/api/useFetchOgp.ts
  front/src/hooks/auth/useCheckAuth.ts
  front/src/hooks/auth/useSignInAnonymously.ts
  front/src/hooks/auth/useSignOut.ts
  front/src/hooks/button/useButtonBookmark.ts
  front/src/hooks/copy/useCopyTextToClipBoard.ts
  front/src/hooks/firestore/bookmark/useCreateBookmark.ts
  front/src/hooks/firestore/bookmark/useDeleteBookmark.ts
  front/src/hooks/firestore/user/useUpdateUser.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/hooks/form/useFormCreateUpdateUser.ts
  front/src/pages/_app.tsx
  front/yarn.lock
Labels: Markup, 🥳LGTM

#201 🈂️ SEO追加
  front/package.json
  front/public/favicon.ico
  front/public/images/ogp.png
  front/src/components/SEOs/DefaultSeo.tsx
  front/src/components/SEOs/index.ts
  front/src/pages/_app.tsx
  front/yarn.lock
Labels: 🥳LGTM

#204 👍 ぐるぐるを真ん中にする
  front/src/components/Cards/CardLinkEdit.tsx
  front/yarn.lock
Labels: Review Required, Markup

#205 editできる人だけeditボタンを表示する
  front/src/pages/[traveliId]/index.tsx
Labels: 🥳LGTM, bug
