Repository traveli-dev/traveli-web, pull requests merged in 2022-08, with the labels that each got.

#169 👳‍♂️トラベリンクが無いときに表示するテキストのコンポーネントを作成する
  front/src/components/Texts/TextEmpty.tsx
  front/src/components/Texts/index.ts
Labels: Review Required

#181 🕓QRコード中央のアイコンを削除
  front/src/components/Modals/ModalQrCode.tsx
Labels: Review Required, 🥳LGTM

#182 ぐるぐるを直すなど
  front/src/components/Forms/FormCreateUpdateLinks.tsx
  front/src/components/Forms/FormCreateUpdateUser.tsx
  front/src/components/Forms/index.ts
  front/src/hooks/auth/useCheckAuth.tsx
  front/src/hooks/auth/useSignInAnonymously.ts
  front/src/hooks/auth/useSignInGoogle.ts
  front/src/hooks/firestore/user/useCreateUser.ts
  front/src/hooks/firestore/user/useGetUser.ts
  front/src/hooks/firestore/user/useUpdateUser.ts
  front/src/hooks/form/useFormCreateUpdateLinks.ts
  front/src/hooks/form/useFormCreateUpdateUser.ts
  front/src/hooks/input/index.ts
  front/src/hooks/input/useInputImage.ts
  front/src/hooks/load/useLoadImage.ts
  front/src/hooks/upload/useUploadImage.ts
  front/src/pages/index.tsx
  front/src/pages/user.tsx
  front/src/recoil/atoms/history.ts
  front/src/recoil/atoms/index.ts
  front/src/recoil/keys.ts
  front/src/types/db/user.ts
Labels: Review Required, Logic, Markup
